apiVersion: apps/v1
kind: Deployment
metadata:
  name: msrestler
  labels:
    app: msrestler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msrestler
  template:
    metadata:
      labels:
        app: msrestler
    spec:
      containers:
      - image: mysql
        name: msrestler
